server:
  port: 8081

logging:
  level:
    root: INFO
    web: DEBUG
    sql: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: true
  application:
  name: blog
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Hong_Kong&characterEncoding=UTF-8
    username: *
    password: *
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
# mybatis命名规则
mybatis:
  configuration:
    map-underscore-to-camel-case: true
# shiro
shiro:
  enabled: true
web:
  enabled: true


