package icu.nickxiao.model.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   时间记录
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table time_record
 */
public class TimeRecord implements Serializable {
    /**
     * Database Column Remarks:
     *   blog id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.id")
    private Long id;

    /**
     * Database Column Remarks:
     *   服务器起始运行时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.timestamp")
    private LocalDateTime timestamp;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.created")
    private LocalDateTime created;

    /**
     * Database Column Remarks:
     *   更新时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.updated")
    private LocalDateTime updated;

    /**
     * Database Column Remarks:
     *   删除时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.deleted")
    private LocalDateTime deleted;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: time_record")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: time_record")
    public TimeRecord withId(Long id) {
        this.setId(id);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.timestamp")
    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: time_record")
    public TimeRecord withTimestamp(LocalDateTime timestamp) {
        this.setTimestamp(timestamp);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.timestamp")
    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.created")
    public LocalDateTime getCreated() {
        return created;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: time_record")
    public TimeRecord withCreated(LocalDateTime created) {
        this.setCreated(created);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.created")
    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.updated")
    public LocalDateTime getUpdated() {
        return updated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: time_record")
    public TimeRecord withUpdated(LocalDateTime updated) {
        this.setUpdated(updated);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.updated")
    public void setUpdated(LocalDateTime updated) {
        this.updated = updated;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.deleted")
    public LocalDateTime getDeleted() {
        return deleted;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: time_record")
    public TimeRecord withDeleted(LocalDateTime deleted) {
        this.setDeleted(deleted);
        return this;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: time_record.deleted")
    public void setDeleted(LocalDateTime deleted) {
        this.deleted = deleted;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: time_record")
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TimeRecord other = (TimeRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTimestamp() == null ? other.getTimestamp() == null : this.getTimestamp().equals(other.getTimestamp()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getUpdated() == null ? other.getUpdated() == null : this.getUpdated().equals(other.getUpdated()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: time_record")
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTimestamp() == null) ? 0 : getTimestamp().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getUpdated() == null) ? 0 : getUpdated().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: time_record")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", timestamp=").append(timestamp);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}